@echo off
echo Staging updated files...
git add .
echo Committing changes...
git commit -m "Configure production deployment settings and requirements"
echo Pushing to GitHub...
git push origin main
echo Done!
pause
