@echo off
echo Initializing Git repository...
git init
echo Staging files...
git add .
echo Committing files...
git commit -m "Initial commit - Employee Leave Management System"
echo Setting default branch to main...
git branch -M main
echo Setting remote repository...
git remote remove origin >nul 2>&1
git remote add origin https://github.com/jayavardhan-28/employee-leave-management.git
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
